### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by lucasvperini** [raccoon-dev/Dropbox#1]
Hey!

It's possible to add the share link function?
I REALLY need it, will be VERY awesome.

Thanks.

**Comment by raccoon-dev** [comment]
Hi lvp11. Unfortunately, i can't find any details about sharing commands in Dropbox documentation. If you will have more lucky, please copy that part here.
[Dropbox documentation](https://www.dropbox.com/developers/documentation/http/documentation#sharing-create_shared_link_with_settings)

**Comment by lucasvperini** [comment]
Hey!
Thanks for answering me.
Here's the requested API doc: https://www.dropbox.com/developers/documentation/http/documentation#sharing-create_shared_link
and
https://www.dropbox.com/developers/documentation/http/documentation#sharing-get_shared_links

These functions are for creating and getting a shared link from a specified file/folder.

It will be awesome to have it on your software.

Thank you very much!

**Comment by raccoon-dev** [comment]
Can you copy that part and paste it here? Sharing commands should be after command "/upload_session/start", but after that command i can see empty sections "paper", "team", "team_log", and next command is "/features/get_values" in "users" section. Sharing section exists on commands list only.

**Comment by lucasvperini** [comment]
Hey!

Sure!
I've added a zip file containing an index.html with the text data and screenshoots of both API calls, hope you can read and do it.

Thank you a lot!

[Dropbox share api.zip](https://github.com/raccoon-dev/Dropbox/files/4403039/Dropbox.share.api.zip)

**Comment by lucasvperini** [comment]
Hey!

Have you made anything about this?

I don't want to be annoying, this is not your obligation, I'm just asking.

Thank you!

**Comment by raccoon-dev** [comment]
Hi lvp11.

I will add that commands probably after weekend. 
BTW thanks for tip with html sources. I can't see sharing commands in browser but they are visible in sources.  Thanks.

**Comment by lucasvperini** [comment]
Hey!

Cool!! Very nice to hear that, i'm looking forward to it, it sure will be very good and will help me and the community a lot!

Thank you a lot mate!

**Comment by raccoon-dev** [comment]
Added functions:

- List Shared Links = '/2/sharing/list_shared_links';
- Delete Shared Link = '/2/sharing/revoke_shared_link';
- Create Shared Link = '/2/sharing/create_shared_link_with_settings' (with default settings)
